import('./tests/p5.Master.js');
import('./tests/p5.Distortion.js');
import('./tests/p5.Effect.js');
import('./tests/p5.Filter.js');
import('./tests/p5.FFT.js');
import('./tests/p5.Compressor.js');
import('./tests/p5.EQ.js');
import('./tests/p5.AudioIn.js');
import('./tests/p5.AudioVoice.js');
import('./tests/p5.MonoSynth.js');
import('./tests/p5.PolySynth.js');
import('./tests/p5.SoundRecorder.js');
import('./tests/p5.SoundFile.js')
import('./tests/p5.Amplitude.js')
import('./tests/p5.Oscillator.js')